services:
  # Serveur PHP-FPM
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/symfony:cached
    depends_on:
      - database
    environment:
      DATABASE_URL: "mysql://user:password@database:3306/symfony?serverVersion=8.0"
      APP_ENV: dev
      APP_SECRET: ${APP_SECRET:-24e17c47ffb8445c9adca82364913518}

  # Serveur web Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "8050:80"
    volumes:
      - ./:/var/www/symfony:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # Base de données MySQL
  database:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql:rw
    command: ["--default-authentication-plugin=mysql_native_password"]

  # Service Adminer pour la gestion de la base de données
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - database

#  # Service Node pour gérer les assets (Webpack Encore)
#  node:
#    image: node:lts
#    volumes:
#      - ./:/var/www/symfony:cached
#    working_dir: /var/www/symfony
#    command: ["tail", "-f", "/dev/null"]

volumes:
  db-data: